import { getKv } from "./kv.ts";
import { sha256Hex } from "./utils.ts";

/**
 * Affinity must expire no later than the Codex auth-pool warm-cache lifetime.
 * There is deliberately no local affinity cache: every keyed request rechecks
 * the durable record before it may alter normal account ordering.
 */
export const CODEX_ACCOUNT_AFFINITY_TTL_MS = 5 * 60_000;
export const CODEX_ACCOUNT_AFFINITY_KV_PREFIX = ["uos_ai", "codex_account_affinity", "v1"] as const;

const OPAQUE_SHA256_HEX = /^[0-9a-f]{64}$/;

const containsControlCharacter = (value: string): boolean => {
  for (let index = 0; index < value.length; index += 1) {
    const code = value.charCodeAt(index);
    if (code <= 0x1f || code === 0x7f) return true;
  }
  return false;
};

export type CodexAccountAffinityIdentity = Readonly<{
  /** The final component is a domain-separated digest, never a raw principal or cache key. */
  kvKey: readonly ["uos_ai", "codex_account_affinity", "v1", string];
}>;

type CodexAccountAffinityRecord = Readonly<{
  account_cohort_hash: string;
  expires_at_ms: number;
}>;

const safelyScopedPrincipal = (principal: string | null | undefined): string | null => {
  const normalized = typeof principal === "string" ? principal.trim() : "";
  if (!normalized || normalized.length > 1_024 || containsControlCharacter(normalized)) return null;

  // Repository-wide and method-wide principals are intentionally excluded.
  // These scopes can represent multiple people, so they cannot safely own an
  // account-affinity record. The accepted forms are generated by handler.ts
  // from stable per-key, per-user, or bearer-credential identities.
  if (normalized.startsWith("api-key:")) {
    return normalized.length > "api-key:".length ? normalized : null;
  }
  if (normalized.startsWith("passkey-user:")) {
    return normalized.length > "passkey-user:".length ? normalized : null;
  }
  if (normalized.startsWith("bearer-sha256:")) {
    const digest = normalized.slice("bearer-sha256:".length);
    return OPAQUE_SHA256_HEX.test(digest) ? normalized : null;
  }
  return null;
};

const nonblankExplicitCacheKey = (value: string | null | undefined): string | null =>
  typeof value === "string" && value.trim().length > 0 && value.length <= 16_384 && !containsControlCharacter(value)
    ? value
    : null;

/**
 * The key uses one digest over both caller-controlled inputs. Keeping the
 * inputs length-delimited prevents boundary ambiguity without persisting or
 * exposing either value.
 */
export const deriveCodexAccountAffinityIdentity = async (
  principal: string | null | undefined,
  explicitPromptCacheKey: string | null | undefined,
): Promise<CodexAccountAffinityIdentity | null> => {
  const scopedPrincipal = safelyScopedPrincipal(principal);
  const cacheKey = nonblankExplicitCacheKey(explicitPromptCacheKey);
  if (scopedPrincipal === null || cacheKey === null) return null;
  const digest = await sha256Hex(
    `uos_ai\u0000codex_account_affinity_identity_v1\u0000${scopedPrincipal.length}\u0000${scopedPrincipal}\u0000${cacheKey.length}\u0000${cacheKey}`,
  );
  return { kvKey: [...CODEX_ACCOUNT_AFFINITY_KV_PREFIX, digest] };
};

const parseRecord = (value: unknown, now: number): CodexAccountAffinityRecord | null => {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  const record = value as Record<string, unknown>;
  const accountCohortHash = record.account_cohort_hash;
  const expiresAtMs = record.expires_at_ms;
  if (
    typeof accountCohortHash !== "string" || !OPAQUE_SHA256_HEX.test(accountCohortHash) ||
    typeof expiresAtMs !== "number" || !Number.isSafeInteger(expiresAtMs) || expiresAtMs <= now
  ) {
    return null;
  }
  return { account_cohort_hash: accountCohortHash, expires_at_ms: expiresAtMs };
};

/** Returns only the opaque cohort hash. KV outage or malformed data is a normal no-affinity result. */
export const readCodexAccountAffinity = async (
  identity: CodexAccountAffinityIdentity | null,
  now = Date.now(),
): Promise<string | null> => {
  if (!identity || !Number.isSafeInteger(now)) return null;
  try {
    const kv = await getKv();
    if (!kv) return null;
    const entry = await kv.get<CodexAccountAffinityRecord>(identity.kvKey, { consistency: "strong" });
    return parseRecord(entry.value, now)?.account_cohort_hash ?? null;
  } catch {
    return null;
  }
};

/**
 * A successful completed Codex response can replace an old preference. The
 * durable payload deliberately has only its opaque cohort and expiry; Deno KV
 * enforces the same bound with expireIn so no cleanup process is required.
 */
export const recordCodexAccountAffinity = async (
  identity: CodexAccountAffinityIdentity | null,
  accountCohortHash: string | null | undefined,
  now = Date.now(),
): Promise<void> => {
  if (
    !identity || typeof accountCohortHash !== "string" || !OPAQUE_SHA256_HEX.test(accountCohortHash) ||
    !Number.isSafeInteger(now) || now > Number.MAX_SAFE_INTEGER - CODEX_ACCOUNT_AFFINITY_TTL_MS
  ) {
    return;
  }
  const expiresAtMs = now + CODEX_ACCOUNT_AFFINITY_TTL_MS;
  try {
    const kv = await getKv();
    if (!kv) return;
    await kv.set(
      identity.kvKey,
      { account_cohort_hash: accountCohortHash, expires_at_ms: expiresAtMs },
      { expireIn: CODEX_ACCOUNT_AFFINITY_TTL_MS },
    );
  } catch {
    // Affinity is best effort. It must never delay or change inference routing.
  }
};
